version: "3"
services:
  app:
    build: .
    ports:
      - "3100:3100"
    depends_on:
      - db
  db:
    image: "microsoft.com/mssql/server:2022-latest"
    restart: always
    environment:
      MSSQL_USER: sa
      MSSQL_PASSWORD: *Cambiar123*
      MSSQL_DB: sqlunal
    ports:
      - "1443:1443"